import { additionalRevolutionaryWarSources } from './revolutionary-war.sources';
import type { HistoryLiveProjectConfig } from '../../templates/history-live/domain/history-live.models';

export const historyLiveRevolutionaryWarConfig: HistoryLiveProjectConfig = {
  schemaVersion: '1.0',
  template: { id: 'history-live-broadcast', version: '1.1' },
  projectId: 'history-live-revolutionary-war',
  projectVersion: '1.1.0',
  title: 'History Live: The Revolutionary War',
  event: 'The American Revolutionary War',
  seasonLabel: 'Special Report · 1763–1783',
  historicalWindow: 'Revolutionary era · 1763–1783',
  broadcastDateLabel: 'Friday · 1:15 PM',
  drivingQuestion:
    'If modern news networks covered the Revolutionary War as it unfolded, what stories would each side tell—and what evidence would they emphasize?',
  networks: [
    {
      id: 'continental-news-network',
      side: 'patriot',
      name: 'Continental News Network',
      shortName: 'CNN 1776',
      monogram: 'C',
      communities: ['Continental forces', 'Independence leaders', 'Patriot civilians'],
      deskLabel: 'The Liberty Desk',
      perspective:
        'Report with attention to Patriot leaders, Continental forces, independence supporters, and civilians living through revolution.',
      accent: '#7ca8c9',
      deskImageUrl: '/history-live/continental-news-desk-v2.webp',
      deskImageAlt:
        'A modern Continental broadcast desk inside a busy 1776 Philadelphia printing and assembly room, with the Pennsylvania State House visible through tall windows.',
      deskLocationLabel: 'Philadelphia · July 1776',
    },
    {
      id: 'crown-news-network',
      side: 'british',
      name: 'Crown News Network',
      shortName: 'CROWN',
      monogram: 'CR',
      communities: ['British command', 'Parliament and Crown', 'Loyalist communities'],
      deskLabel: 'The Royal Desk',
      perspective:
        'Report with attention to Crown leadership, British forces, Parliament, Loyalist communities, and an empire fighting across the Atlantic.',
      accent: '#d78a78',
      deskImageUrl: '/history-live/crown-news-desk-v2.webp',
      deskImageAlt:
        'A modern Crown broadcast desk inside a candlelit 1777 Westminster press room, with rain-darkened London and parliamentary buildings beyond the windows.',
      deskLocationLabel: 'Westminster, London · 1777',
    },
  ],
  beats: [
    { id: 'breaking', label: 'Breaking News', glyph: 'NOW', prompt: 'What just happened?' },
    { id: 'politics', label: 'Politics', glyph: 'POL', prompt: 'What are leaders deciding?' },
    {
      id: 'military',
      label: 'Military',
      glyph: 'MIL',
      prompt: 'What is changing on the battlefield?',
    },
    {
      id: 'people',
      label: 'People',
      glyph: 'PPL',
      prompt: 'How are civilians experiencing the war?',
    },
    { id: 'world', label: 'World', glyph: 'WRLD', prompt: 'How is the Atlantic world involved?' },
    {
      id: 'fact-check',
      label: 'Fact Check',
      glyph: '✓?',
      prompt: 'Which claim can the evidence test?',
    },
    {
      id: 'communication',
      label: 'Media',
      glyph: 'WIRE',
      prompt: 'How are ideas shaping opinion?',
    },
    { id: 'geography', label: 'Geography', glyph: 'MAP', prompt: 'Why does place matter?' },
  ],
  storyLeads: [
    {
      id: 'lead-patriot-lexington',
      asOfDate: '1775-04-30',
      sourceIds: ['source-parker', 'source-gage'],
      side: 'patriot',
      beatId: 'breaking',
      headline: 'Shots fired at Lexington and Concord',
      question: 'What happened on the road from Boston, and why did the fighting spread?',
      format: 'Field Report',
      location: 'Massachusetts · April 1775',
      whyNow: 'Armed conflict has begun between colonial militia and British regulars.',
    },
    {
      id: 'lead-patriot-declaration',
      asOfDate: '1776-07-31',
      sourceIds: ['source-declaration', 'source-king-proclamation', 'source-abigail'],
      side: 'patriot',
      beatId: 'politics',
      headline: 'Colonies declare independence',
      question: 'How did the Declaration change the purpose and stakes of the conflict?',
      format: 'Political Analysis',
      location: 'Philadelphia · July 1776',
      whyNow: 'Congress has publicly broken political ties with Great Britain.',
    },
    {
      id: 'lead-patriot-valley-forge',
      asOfDate: '1777-12-31',
      sourceIds: ['source-valley-forge-orders', 'source-valley-forge-supplies'],
      side: 'patriot',
      beatId: 'people',
      headline: 'Inside the winter camp at Valley Forge',
      question: 'How did shortages and reorganization shape the Continental Army?',
      format: 'Human-Interest Story',
      location: 'Pennsylvania · Winter 1777–1778',
      whyNow: 'The army is building winter quarters while struggling to secure supplies.',
    },
    {
      id: 'lead-patriot-saratoga',
      asOfDate: '1778-02-28',
      sourceIds: ['source-saratoga-convention', 'source-treaty-france', 'source-gates-logistics'],
      side: 'patriot',
      beatId: 'world',
      headline: 'Saratoga victory changes the diplomatic map',
      question: 'Why did the American victory help persuade France to enter the war?',
      format: 'Historical Explainer',
      location: 'New York & Paris · 1777–1778',
      whyNow: 'A battlefield result may turn a colonial rebellion into a global war.',
    },
    {
      id: 'lead-patriot-promises',
      asOfDate: '1777-01-31',
      sourceIds: ['source-declaration', 'source-hall', 'source-abigail'],
      side: 'patriot',
      beatId: 'fact-check',
      headline: 'Who was included in the promise of independence?',
      question: 'How did revolutionary ideals compare with lived freedom in 1776?',
      format: 'Fact Check',
      location: 'Thirteen states · 1776–1777',
      whyNow: 'The language of equality invites questions about who could claim those rights.',
    },
    {
      id: 'lead-british-taxation',
      asOfDate: '1765-10-31',
      sourceIds: ['source-stamp-act', 'source-stamp-resolves'],
      side: 'british',
      beatId: 'politics',
      headline: 'Parliament defends colonial revenue policy',
      question: 'Why did British leaders believe the colonies should help pay imperial costs?',
      format: 'Political Analysis',
      location: 'Westminster · 1765',
      whyNow: 'New duties are provoking organized resistance across the colonies.',
    },
    {
      id: 'lead-british-new-york',
      asOfDate: '1776-09-30',
      sourceIds: ['source-new-york-defense', 'source-king-proclamation'],
      side: 'british',
      beatId: 'military',
      headline: 'Why New York is central to Crown strategy',
      question: 'How could control of New York divide the rebellion and support the fleet?',
      format: 'Military Analysis',
      location: 'New York · 1776',
      whyNow: 'British forces are concentrating around a major Atlantic port.',
    },
    {
      id: 'lead-british-loyalists',
      asOfDate: '1783-12-31',
      sourceIds: ['source-paris-loyalists', 'source-king-proclamation'],
      side: 'british',
      beatId: 'people',
      headline: 'Loyalist communities face a dangerous choice',
      question: 'Why did some colonists remain loyal, and what risks did that create?',
      format: 'Human-Interest Story',
      location: 'British North America · 1775–1783',
      whyNow: 'The conflict is dividing neighbors, families, merchants, and communities.',
    },
    {
      id: 'lead-british-saratoga',
      asOfDate: '1777-10-31',
      sourceIds: ['source-saratoga-convention', 'source-gates-logistics'],
      side: 'british',
      beatId: 'military',
      headline: 'Saratoga exposes a strategy in crisis',
      question: 'Why did Burgoyne’s campaign fail, and what must British command change?',
      format: 'Military Analysis',
      location: 'New York · October 1777',
      whyNow: 'An entire British field army has surrendered far from New York City.',
    },
    {
      id: 'lead-british-yorktown',
      asOfDate: '1781-12-31',
      sourceIds: ['source-yorktown-map', 'source-yorktown-articles'],
      side: 'british',
      beatId: 'breaking',
      headline: 'Cornwallis surrenders at Yorktown',
      question: 'How did land and naval pressure trap the British army in Virginia?',
      format: 'Breaking News',
      location: 'Virginia · October 1781',
      whyNow: 'A major British army has surrendered, raising urgent questions in London.',
    },
  ],
  assignmentScenes: [
    {
      side: 'patriot',
      imageUrl: '/history-live/patriot-assignment-newsroom.webp',
      imageAlt:
        'Five passionate Revolutionary-era advocates call for attention in a frantic Philadelphia print shop, raising blank newspapers for stories about Lexington, independence, Continental soldiers, revolutionary promises, and the French alliance.',
      locationLabel: 'Philadelphia News Exchange · 1776–1778',
      advocates: [
        {
          leadId: 'lead-patriot-lexington',
          advocateLabel: 'Massachusetts militia courier',
          leftPercent: 6,
          topPercent: 3.6,
          widthPercent: 14.3,
          heightPercent: 31.4,
        },
        {
          leadId: 'lead-patriot-declaration',
          advocateLabel: 'Philadelphia printer',
          leftPercent: 32.9,
          topPercent: 3.4,
          widthPercent: 13.2,
          heightPercent: 35.4,
        },
        {
          leadId: 'lead-patriot-valley-forge',
          advocateLabel: 'Continental soldier',
          leftPercent: 81.6,
          topPercent: 4.5,
          widthPercent: 15.5,
          heightPercent: 35.6,
        },
        {
          leadId: 'lead-patriot-promises',
          advocateLabel: 'Free Black petitioner',
          leftPercent: 37.4,
          topPercent: 55.9,
          widthPercent: 19.3,
          heightPercent: 40,
        },
        {
          leadId: 'lead-patriot-saratoga',
          advocateLabel: 'Continental alliance liaison',
          leftPercent: 69.8,
          topPercent: 54,
          widthPercent: 18.6,
          heightPercent: 39.8,
        },
      ],
    },
    {
      side: 'british',
      imageUrl: '/history-live/british-assignment-newsroom.webp',
      imageAlt:
        'Five passionate Crown and Loyalist advocates call for attention in a frantic Westminster print shop, raising blank newspapers for stories about taxation, British strategy, divided Loyalist communities, Saratoga, and Yorktown.',
      locationLabel: 'Westminster News Exchange · 1777–1781',
      advocates: [
        {
          leadId: 'lead-british-taxation',
          advocateLabel: 'Parliamentary revenue clerk',
          leftPercent: 4.1,
          topPercent: 19.6,
          widthPercent: 21.1,
          heightPercent: 27.6,
        },
        {
          leadId: 'lead-british-saratoga',
          advocateLabel: 'British campaign clerk',
          leftPercent: 54.5,
          topPercent: 8,
          widthPercent: 14.7,
          heightPercent: 31.7,
        },
        {
          leadId: 'lead-british-new-york',
          advocateLabel: 'Royal Navy chart officer',
          leftPercent: 77.3,
          topPercent: 2.7,
          widthPercent: 15.7,
          heightPercent: 35.3,
        },
        {
          leadId: 'lead-british-loyalists',
          advocateLabel: 'Loyalist refugee',
          leftPercent: 14,
          topPercent: 50.2,
          widthPercent: 19.6,
          heightPercent: 35,
        },
        {
          leadId: 'lead-british-yorktown',
          advocateLabel: 'British field correspondent',
          leftPercent: 67,
          topPercent: 47.1,
          widthPercent: 19.4,
          heightPercent: 40.4,
        },
      ],
    },
  ],
  sources: [
    ...additionalRevolutionaryWarSources,
    {
      id: 'source-declaration',
      availableOn: '1776-07-04',
      primary: true,
      excerptKind: 'summary',
      title: 'Declaration of Independence',
      creator: 'Second Continental Congress',
      dateLabel: 'July 4, 1776',
      sourceType: 'Official declaration',
      perspective: 'patriot',
      excerpt: 'The document announces separation and presents a public case against the Crown.',
      context:
        'Read the list of grievances as an argument created for domestic and international audiences—not as a neutral summary of events.',
      citation: 'National Archives, Declaration of Independence: A Transcription.',
      url: 'https://www.archives.gov/founding-docs/declaration-transcript',
      tags: ['politics', 'independence', 'rights'],
    },
    {
      id: 'source-stamp-act',
      availableOn: '1765-03-22',
      primary: true,
      excerptKind: 'summary',
      title: 'The Stamp Act',
      creator: 'Parliament of Great Britain',
      dateLabel: 'March 22, 1765',
      sourceType: 'Law',
      perspective: 'british',
      excerpt: 'The act imposed duties on many legal and printed materials in the colonies.',
      context:
        'The law’s title states that the revenue would help cover expenses of defending and protecting British colonies.',
      citation: 'UK Parliament, The Stamp Act, 1765.',
      url: 'https://www.parliament.uk/about/living-heritage/evolutionofparliament/legislativescrutiny/parliament-and-empire/collections1/collections1/stamp-act/',
      tags: ['taxation', 'parliament', 'causes'],
    },
    {
      id: 'source-king-proclamation',
      imageUrl: 'https://www.archives.gov/files/founding-docs/proclamation1-lg.jpg',
      imageAlt:
        'First page of King George III’s proclamation of August 23, 1775; full context and document image are linked below.',
      availableOn: '1775-08-23',
      primary: true,
      excerptKind: 'summary',
      title: 'Proclamation for Suppressing Rebellion',
      creator: 'King George III',
      dateLabel: 'August 23, 1775',
      sourceType: 'Royal proclamation',
      perspective: 'british',
      excerpt:
        'The Crown described armed colonial resistance as open rebellion and called for order to be restored.',
      context:
        'Consider how the language of rebellion frames the conflict differently from the language of revolution.',
      citation:
        'U.S. National Archives, Proclamation for Suppressing Rebellion and Sedition, image in How Did It Happen?',
      url: 'https://www.archives.gov/founding-docs/declaration/how-did-it-happen',
      tags: ['crown', 'rebellion', 'politics'],
    },
    {
      id: 'source-valley-forge-orders',
      availableOn: '1777-12-20',
      primary: true,
      excerptKind: 'summary',
      title: 'General Orders at Valley Forge',
      creator: 'George Washington’s headquarters',
      dateLabel: 'December 20, 1777',
      sourceType: 'Military orders',
      perspective: 'patriot',
      excerpt: 'Orders directed soldiers to preserve timber while building defensible winter huts.',
      context:
        'This operational document shows the practical work of establishing the camp. It does not by itself measure every hardship soldiers faced.',
      citation: 'Founders Online, National Archives, General Orders, 20 December 1777.',
      url: 'https://founders.archives.gov/documents/Washington/03-12-02-0584',
      tags: ['military', 'valley-forge', 'logistics'],
    },
    {
      id: 'source-valley-forge-supplies',
      availableOn: '1777-12-23',
      primary: true,
      excerptKind: 'summary',
      title: 'Washington reports a supply crisis',
      creator: 'George Washington to Henry Laurens',
      dateLabel: 'December 23, 1777',
      sourceType: 'Command letter',
      perspective: 'patriot',
      excerpt:
        'Washington warned Congress that the army could starve, dissolve, or disperse without major changes in supply.',
      context:
        'A commanding officer may emphasize urgency to prompt action. Compare the letter with orders, inventories, and soldiers’ accounts.',
      citation: 'Founders Online, National Archives, George Washington to Henry Laurens.',
      url: 'https://founders.archives.gov/documents/Washington/03-12-02-0628',
      tags: ['valley-forge', 'supplies', 'military'],
    },
    {
      id: 'source-treaty-france',
      availableOn: '1778-02-06',
      primary: true,
      excerptKind: 'summary',
      title: 'Treaty of Alliance with France',
      creator: 'United States and France',
      dateLabel: 'February 6, 1778',
      sourceType: 'International treaty',
      perspective: 'international',
      excerpt:
        'The agreement formalized military cooperation between France and the United States against Great Britain.',
      context:
        'Treaty language reveals commitments and goals. It does not explain every strategic motive behind the alliance.',
      citation: 'Avalon Project, Treaty of Alliance Between the United States and France.',
      url: 'https://avalon.law.yale.edu/18th_century/fr1788-2.asp',
      tags: ['france', 'world', 'saratoga'],
    },
    {
      id: 'source-loyalist-claims',
      title: 'Ann Nevil petitions for Loyalist relief',
      creator: 'Ann Nevil; petition discussed by The National Archives (UK)',
      dateLabel: 'Wartime petition; modern archival interpretation',
      availableOn: '2026-09-04',
      primary: false,
      excerptKind: 'summary',
      sourceType: 'Archival case study with petition evidence',
      perspective: 'british',
      excerpt: 'A Loyalist refugee sought financial support from British authorities in New York.',
      context:
        'This modern archival article identifies a particular petitioner. Use it retrospectively; separate the underlying petition from the curator’s interpretation. One claimant cannot represent all Loyalists.',
      citation: 'The National Archives (UK), Ann Nevil: The most Notorious Malafactor imaginable.',
      url: 'https://www.nationalarchives.gov.uk/explore-the-collection/stories/ann-nevil-the-most-notorious-malafactor-imaginable/',
      tags: ['loyalists', 'people', 'women', 'petition'],
    },
    {
      id: 'source-yorktown-map',
      availableOn: '1781-12-31',
      primary: true,
      excerptKind: 'summary',
      title: 'Plan des ouvrages faits à York-town en Virginie',
      creator: 'Unidentified mapmaker; Library of Congress manuscript map',
      dateLabel: '1781; exact completion date unknown',
      sourceType: 'Map',
      perspective: 'multiple',
      excerpt:
        'An unfinished manuscript plan records siege works around Yorktown. Examine which positions are drawn and which details remain incomplete.',
      context:
        'Maps emphasize selected terrain and movement. Check dates, scale, legend, and the mapmaker’s purpose.',
      citation:
        'Library of Congress, Plan des ouvrages faits à York-town en Virginie, 1781, gm71002177.',
      url: 'https://www.loc.gov/item/gm71002177/',
      tags: ['yorktown', 'geography', 'military'],
    },
  ],
  reportFormats: [
    'Breaking News',
    'Field Report',
    'Investigative Report',
    'Fact Check',
    'Human-Interest Story',
    'Military Analysis',
    'Political Analysis',
    'Historical Explainer',
  ],
  seedSegments: [
    {
      id: 'segment-lexington',
      reporter: 'Avery Chen',
      side: 'patriot',
      networkName: 'Continental News Network',
      headline: 'Lexington: what we know tonight',
      desk: 'Breaking News',
      durationSeconds: 145,
      startLabel: '1:18 PM',
      ready: true,
      visualLabel: 'Massachusetts road map · April 1775',
    },
    {
      id: 'segment-crown-policy',
      reporter: 'Mateo Ruiz',
      side: 'british',
      networkName: 'Crown News Network',
      headline: 'Why Parliament says the colonies must contribute',
      desk: 'Politics',
      durationSeconds: 162,
      startLabel: '1:21 PM',
      ready: true,
      visualLabel: 'Stamp Act · Parliamentary record',
    },
    {
      id: 'segment-declaration',
      reporter: 'Noor Williams',
      side: 'patriot',
      networkName: 'Continental News Network',
      headline: 'Congress votes for a new nation',
      desk: 'Liberty Desk',
      durationSeconds: 176,
      startLabel: '1:24 PM',
      ready: true,
      visualLabel: 'Declaration broadside · Philadelphia',
    },
    {
      id: 'segment-loyalists',
      reporter: 'Emery Jones',
      side: 'british',
      networkName: 'Crown News Network',
      headline: 'The war next door: Loyalist families under pressure',
      desk: 'People',
      durationSeconds: 151,
      startLabel: '1:28 PM',
      ready: true,
      visualLabel: 'Community testimony · British North America',
    },
    {
      id: 'segment-france',
      reporter: 'Kai Thompson',
      side: 'patriot',
      networkName: 'Continental News Network',
      headline: 'France enters the war',
      desk: 'World',
      durationSeconds: 169,
      startLabel: '1:31 PM',
      ready: true,
      visualLabel: 'Atlantic alliance map · 1778',
    },
    {
      id: 'segment-yorktown',
      reporter: 'Lina Patel',
      side: 'british',
      networkName: 'Crown News Network',
      headline: 'After Yorktown: the questions facing London',
      desk: 'Analysis',
      durationSeconds: 158,
      startLabel: '1:35 PM',
      ready: true,
      visualLabel: 'Yorktown siege lines · 1781',
    },
  ],
  broadcastStartMinutes: 13 * 60 + 15,
  rubric: [
    {
      id: 'accuracy',
      label: 'Historical accuracy',
      expectation:
        'Place the report in time and explain what could be known then. Identify later evidence in retrospective reports.',
    },
    {
      id: 'sourcing',
      label: 'Source analysis',
      expectation:
        'Identify creator, audience, purpose, and limits. Cite specific passages or map observations, including a primary source.',
    },
    {
      id: 'corroboration',
      label: 'Corroboration',
      expectation:
        'Compare evidence across documents. Explain why it supports or challenges each major claim.',
    },
    {
      id: 'perspective',
      label: 'Perspective',
      expectation:
        'Present the strongest opposing interpretation fairly. Recognize that communities have distinct interests beyond two networks.',
    },
    {
      id: 'uncertainty',
      label: 'Responsible uncertainty',
      expectation:
        'Separate fact, interpretation, and unresolved questions. Do not label a claim verified without explaining its basis.',
    },
    {
      id: 'communication',
      label: 'Communication',
      expectation:
        'Create a clear opening, evidence sequence, and conclusion. Provide a readable transcript for recordings.',
    },
    {
      id: 'revision',
      label: 'Reflection and revision',
      expectation:
        'Identify a claim you revised after hearing another report, name the evidence, and explain what changed.',
    },
  ],
  reflectionPrompt:
    'Which claim changed after hearing another network or community? Cite the evidence, explain your earlier reasoning, and describe your revised conclusion.',
};
