import type {
  AutomationProjectConfig,
  CommandType,
  CourseDefinition,
  RobotChallenge,
} from '../../templates/programming-automation/domain/automation.models';
const movement: readonly CommandType[] = ['move-distance', 'move-rotations', 'wait'];
const navigation: readonly CommandType[] = [...movement, 'turn-degrees', 'turn-fraction'];
const delivery: readonly CommandType[] = [...navigation, 'pick-up', 'drop-off'];
const all: readonly CommandType[] = [...delivery, 'repeat'];
const floor = (id: string, name: string): CourseDefinition => ({
  id,
  name,
  widthCm: 400,
  heightCm: 300,
  gridSizeCm: 25,
  startPose: { xCm: 50, yCm: 50, headingDeg: 0 },
  targets: [{ xCm: 50, yCm: 170, headingDeg: 0, label: '120 cm' }],
  toleranceCm: 3,
  obstacles: [],
  packages: [],
  deliveryZones: [],
  checkpoints: [],
  battery: { move: 0.05, turn: 0.01, wait: 0.02, pickup: 2, dropoff: 1, collision: 8 },
  stopOnCollision: true,
});
const courses: readonly CourseDefinition[] = [
  {
    ...floor('calibration', 'Calibration lane'),
    targets: [24, 12, 6, 18].map((distance) => ({
      xCm: 50,
      yCm: 50 + distance,
      headingDeg: 0,
      label: `${distance} cm`,
    })),
  },
  {
    ...floor('parking', 'Precision parking bay'),
    targets: [120, 48, 72, 90, 126].map((distance) => ({
      xCm: 50,
      yCm: 50 + distance,
      headingDeg: 0,
      label: `${distance} cm`,
    })),
  },
  {
    ...floor('turns', 'Turn training'),
    targets: [{ xCm: 150, yCm: 150, headingDeg: 90, label: 'L route · face east' }],
    headingToleranceDeg: 2,
    obstacles: [
      { id: 'barrier', label: 'Keep clear', xCm: 85, yCm: 50, widthCm: 30, heightCm: 70 },
    ],
  },
  {
    ...floor('coordinates', 'Coordinate courier'),
    targets: [{ xCm: 150, yCm: 50, headingDeg: 180, label: 'Return dock (6, 2)' }],
    packages: [{ id: 'parcel-a', label: 'A', xCm: 50, yCm: 125, deliveryZoneId: 'zone-a' }],
    deliveryZones: [{ id: 'zone-a', label: 'A', xCm: 135, yCm: 110, widthCm: 30, heightCm: 30 }],
  },
  {
    ...floor('variables', 'Variable upgrade'),
    targets: [
      { xCm: 150, yCm: 150, headingDeg: 90, label: '100 cm sides' },
      { xCm: 200, yCm: 200, headingDeg: 90, label: '150 cm sides' },
    ],
  },
  {
    ...floor('pattern', 'Warehouse square'),
    startPose: { xCm: 75, yCm: 75, headingDeg: 0 },
    targets: [{ xCm: 75, yCm: 75, headingDeg: 0, label: 'Return to start' }],
    checkpoints: [
      { id: 'north', xCm: 75, yCm: 175, radiusCm: 5 },
      { id: 'east', xCm: 175, yCm: 175, radiusCm: 5 },
      { id: 'south', xCm: 175, yCm: 75, radiusCm: 5 },
    ],
  },
  {
    ...floor('battery', 'Battery emergency'),
    targets: [{ xCm: 250, yCm: 200, headingDeg: 90, label: 'Charging dock' }],
    obstacles: [
      { id: 'shelf', label: 'Storage rack', xCm: 100, yCm: 80, widthCm: 100, heightCm: 80 },
    ],
  },
  {
    ...floor('cargo', 'Cargo delivery'),
    targets: [{ xCm: 250, yCm: 200, headingDeg: 90, label: 'Delivery dock' }],
    packages: [{ id: 'parcel-a', label: 'A · heavy', xCm: 50, yCm: 150, deliveryZoneId: 'zone-a' }],
    deliveryZones: [{ id: 'zone-a', label: 'A', xCm: 235, yCm: 185, widthCm: 30, heightCm: 30 }],
  },
  {
    ...floor('championship', 'Championship arena'),
    targets: [{ xCm: 50, yCm: 50, headingDeg: 180, label: 'Return to the start dock' }],
    packages: [
      { id: 'parcel-a', label: 'A', xCm: 50, yCm: 150, deliveryZoneId: 'zone-a' },
      { id: 'parcel-b', label: 'B', xCm: 250, yCm: 250, deliveryZoneId: 'zone-b' },
    ],
    deliveryZones: [
      { id: 'zone-a', label: 'A', xCm: 135, yCm: 235, widthCm: 30, heightCm: 30 },
      { id: 'zone-b', label: 'B', xCm: 235, yCm: 35, widthCm: 30, heightCm: 30 },
    ],
    obstacles: [
      { id: 'rack', label: 'Storage rack', xCm: 105, yCm: 90, widthCm: 85, heightCm: 110 },
    ],
  },
];
const challenge = (
  id: string,
  title: string,
  week: 1 | 2 | 3,
  courseId: string,
  mission: string,
  commands: readonly CommandType[],
  requiredMath: RobotChallenge['requiredMath'],
  hint: string,
): RobotChallenge => ({
  id,
  title,
  week,
  courseId,
  mission,
  allowedCommands: commands,
  requiredMath,
  skills: requiredMath,
  hint,
});
export const robotDeliveryConfig: AutomationProjectConfig = {
  schemaVersion: '1.0',
  template: { id: 'programming-automation', version: '1.0' },
  projectId: 'robot-delivery-code-lab',
  projectVersion: '1.0.0',
  title: 'Robot Delivery Code Lab',
  subtitle: 'Programming & Automation Challenge',
  initialChallengeId: 'precision-parking',
  championshipChallengeId: 'championship',
  robot: {
    id: 'courier-01',
    name: 'Courier 01',
    wheelDiameterCm: 8,
    distancePerRotationCm: 24,
    loadedDistancePerRotationCm: 24,
    moveSpeed: 20,
    loadedSpeed: 17,
    turnRate: 45,
    radiusCm: 8,
    cargoLimit: 1,
    batteryCapacity: 100,
  },
  courses,
  scoring: { delivery: 35, navigation: 20, efficiency: 20, reliability: 15, prediction: 10 },
  challenges: [
    challenge(
      'calibration-garage',
      'Calibration Garage',
      1,
      'calibration',
      'Measure how far one whole, half and quarter rotation actually carries your robot.',
      movement,
      ['circumference', 'rotation-distance'],
      'Calculate with π ≈ 3.14, then compare that theoretical circumference with measured travel. Measurements may differ.',
    ),
    challenge(
      'precision-parking',
      'Precision Parking',
      1,
      'parking',
      'Park the center of your robot on the selected target. Calculate the rotations before running.',
      movement,
      ['circumference', 'distance-rotations'],
      'Find the distance from the start to your target. Divide it by the measured travel per wheel rotation.',
    ),
    challenge(
      'turn-training',
      'Turn Training',
      1,
      'turns',
      'Follow an L-shaped route around the barrier and finish facing east.',
      navigation,
      ['fraction-turn', 'turn-time'],
      'North is 0°, east is 90°. Convert a fraction of 360° into a turn, then calculate how long the turn takes.',
    ),
    challenge(
      'coordinate-courier',
      'Coordinate Courier',
      1,
      'coordinates',
      'Collect package A at (2, 5), deliver it to (6, 5), then park at (6, 2). Each grid square is 25 cm.',
      delivery,
      ['grid-distance'],
      'Use coordinate changes along one axis at a time. PICK UP and DROP OFF happen only when your code says so.',
    ),
    {
      ...challenge(
        'variable-upgrade',
        'Variable Upgrade',
        2,
        'variables',
        'Reach the far corner using a named SIDE variable. Change the target size, then update the variable.',
        navigation,
        ['grid-distance'],
        'A variable is a named measurement. Define SIDE once, then use SIDE in each MOVE block.',
      ),
      requiresVariable: true,
    },
    {
      ...challenge(
        'warehouse-pattern',
        'Warehouse Pattern',
        2,
        'pattern',
        'Visit every corner of the 100 cm square and return to the start using a repeat block.',
        all,
        ['fraction-turn'],
        'Look for a MOVE and TURN pattern. The robot must visit all three checkpoints before returning.',
      ),
      requiresLoop: true,
      minimumDistance: 395,
      maximumCommands: 6,
    },
    {
      ...challenge(
        'battery-emergency',
        'Battery Emergency',
        2,
        'battery',
        'Reach the charging dock without hitting the rack or using more than 24 battery units.',
        all,
        ['movement-time'],
        'Compare route length and turns. Movement uses 0.05 units/cm; turns use 0.01 units/degree.',
      ),
      batteryCapacity: 24,
    },
    challenge(
      'cargo-delivery',
      'Cargo Delivery',
      2,
      'cargo',
      'Pick up the heavy package, deliver it to zone A, and compare travel time with an empty robot.',
      all,
      ['movement-time'],
      'The loaded robot moves at 17 cm/s instead of 20 cm/s. Update your predicted time.',
    ),
    {
      ...challenge(
        'championship',
        'Robot Command Championship',
        3,
        'championship',
        'Deliver both packages to their matching zones and return to the start. Lock a tested program, then run it autonomously.',
        all,
        [
          'circumference',
          'distance-rotations',
          'fraction-turn',
          'turn-time',
          'grid-distance',
          'movement-time',
        ],
        'Plan around the rack. Package A goes to (6, 10); B goes to (10, 2). You can carry one package at a time.',
      ),
      requiresVariable: true,
      requiresLoop: true,
    },
  ],
};
