import { TestBed } from '@angular/core/testing';
import { provideRouter } from '@angular/router';
import { afterEach, expect, it, vi } from 'vitest';
import data from '../../../../../public/projects/live-strategy-league/project.json';
import { requireLeagueConfig } from '../domain/league-engine';
import { requireLeagueDemo } from '../domain/league-demo';
import { LEAGUE_CONFIG } from '../runtime/league-runtime.service';
import { LeagueFinalDemoComponent } from './league-final-demo.component';

const config = requireLeagueConfig(data);
afterEach(() => { TestBed.resetTestingModule(); vi.useRealTimers(); vi.restoreAllMocks(); });
function render() {
  vi.useFakeTimers();
  TestBed.configureTestingModule({ imports: [LeagueFinalDemoComponent], providers: [provideRouter([]), { provide: LEAGUE_CONFIG, useValue: config }] });
  const fixture = TestBed.createComponent(LeagueFinalDemoComponent);
  fixture.detectChanges();
  return fixture;
}
it('counts down, renders gains and losses, and freezes the final standings without saving practice', () => {
  const save = vi.spyOn(Storage.prototype, 'setItem');
  const fixture = render();
  const demo = fixture.componentInstance;
  const root: HTMLElement = fixture.nativeElement;
  expect(demo.timer()).toBe('00:30');
  expect(demo.leader().name).toBe('Apex');
  expect(root.querySelector('.decision-card h3')?.textContent).toContain('280 units');
  expect(root.querySelector('.decision-options .selected')?.textContent).toContain('Sell 280 units at $20');
  expect(root.querySelector('.trade-heading')?.textContent).toContain('Trade queued');
  vi.advanceTimersByTime(6000); fixture.detectChanges();
  expect(demo.timer()).toBe('00:24');
  expect(demo.leader().name).toBe('Orbit');
  expect(root.querySelector('.trend.up')).not.toBeNull();
  expect(root.querySelector('.trend.down')).not.toBeNull();
  expect(root.querySelector('.trade-heading')?.textContent).toContain('Trade completed');
  expect(root.querySelector('.trade-profit')?.textContent).toContain('+2,800');
  expect(root.querySelector('.trade-impact')?.textContent).toContain('Orbit is now #1');
  vi.advanceTimersByTime(6000); fixture.detectChanges();
  expect(demo.leader().name).toBe('Pulse');
  expect(root.querySelector('.decision-team')?.textContent).toContain('Pulse');
  vi.advanceTimersByTime(18000); fixture.detectChanges();
  expect(demo.timer()).toBe('00:00');
  expect(root.querySelector('.broadcast')?.textContent).toContain('FINAL STANDINGS');
  expect(root.querySelector('.winner')?.textContent).toContain('Nova');
  expect(demo.ranking()[0].score).toBe(33400);
  expect(root.querySelector('.decision-options .selected')?.textContent).toContain('Sell 215 units at $30');
  expect(root.querySelector('.trade-profit')?.textContent).toContain('+4,300');
  expect(root.querySelectorAll('.update-list .trade-recap')).toHaveLength(5);
  const final = demo.snapshot();
  vi.advanceTimersByTime(60000);
  expect(demo.snapshot()).toBe(final);
  expect(save).not.toHaveBeenCalled();
});
it('pauses precisely, resumes, replays from the beginning and cleans up its timer', () => {
  const fixture = render();
  const demo = fixture.componentInstance;
  vi.advanceTimersByTime(5250);
  demo.togglePlayback();
  vi.advanceTimersByTime(10000);
  expect(demo.elapsed()).toBe(5.25);
  demo.togglePlayback();
  vi.advanceTimersByTime(750);
  expect(demo.step()).toBe(1);
  demo.showFinal();
  expect(demo.finished()).toBe(true);
  demo.replay();
  expect(demo.timer()).toBe('00:30');
  expect(demo.leader().name).toBe('Apex');
  expect(demo.decision()?.settled).toBe(false);
  fixture.destroy();
  vi.advanceTimersByTime(60000);
  expect(demo.elapsed()).toBe(0);
});
it('rejects missing teams and unordered or incomplete demo timelines', () => {
  const demo = config.finalDemo!;
  expect(() => requireLeagueDemo({ ...demo, openingScores: {} }, config)).toThrow('INVALID_LEAGUE_DEMO');
  expect(() => requireLeagueDemo({ ...demo, frames: [...demo.frames].reverse() }, config)).toThrow('INVALID_LEAGUE_DEMO');
  expect(() => requireLeagueDemo({ ...demo, frames: demo.frames.slice(0, -1) }, config)).toThrow('INVALID_LEAGUE_DEMO');
  const invalidTrade = structuredClone(demo);
  invalidTrade.frames[0].decision!.unitPrice = 1;
  expect(() => requireLeagueDemo(invalidTrade, config)).toThrow('trade profit matching');
  invalidTrade.frames[0].decision = { ...demo.frames[0].decision!, selected: 99 };
  expect(() => requireLeagueDemo(invalidTrade, config)).toThrow('INVALID_LEAGUE_DEMO');
});
