/** Generated by node scripts/check-solar-calendar.cjs --write-references. */
export const solarCalendarObservations = [
  {
    settings: {
      latitude: 38.83,
      longitude: -104.82,
      zone: 'America/Denver',
      localDate: '2026-03-20',
      minutes: 788.0375166666666,
      utcInstant: '2026-03-20T19:08:02.251Z',
      modelVersion: 'solar-optics-2.0',
      scenarioId: 'march',
      reviewId: 'solar-calendar-example',
      targetId: 'equinox',
      expectedValue: 'blue light',
      actualValue: 'blue light',
      outcome: 'met',
      observationRule: 'noon',
      clockMinutes: 720,
      observationAvailable: 1,
    },
    measurements: [
      {
        label: 'Seasonal event',
        value: 'March equinox',
      },
      {
        label: 'Observation',
        value: '2026-03-20 · 1:08:02 PM · solar noon · America/Denver',
      },
      {
        label: 'Sun altitude',
        value: '51.07°',
      },
      {
        label: 'Sun direction',
        value: '180.36° clockwise from north',
      },
      {
        label: 'Height-only shadow reference',
        value: '1.365 m',
      },
      {
        label: 'Target',
        value: 'Equinoxes · blue light',
      },
      {
        label: 'Expected',
        value: 'blue light',
      },
      {
        label: 'Observed at target centre',
        value: 'blue light',
      },
      {
        label: 'Sculpture surface samples',
        value:
          'Facet 1: faces away; Facet 2: sunlight; Facet 3: sunlight; Facet 4: sunlight; Facet 5: faces away; Facet 6: faces away; Facet 7: faces away; Facet 8: sunlight',
      },
      {
        label: 'Comparison',
        value: 'Matches expectation',
      },
      {
        label: '7 days before',
        value: '2026-03-13: shadow · does not match',
      },
      {
        label: '7 days after',
        value: '2026-03-27: shadow · does not match',
      },
    ],
  },
  {
    settings: {
      latitude: 38.83,
      longitude: -104.82,
      zone: 'America/Denver',
      localDate: '2026-06-21',
      minutes: 782.3351166666667,
      utcInstant: '2026-06-21T19:02:20.107Z',
      modelVersion: 'solar-optics-2.0',
      scenarioId: 'june',
      reviewId: 'solar-calendar-example',
      targetId: 'june',
      expectedValue: 'amber light',
      actualValue: 'amber light',
      outcome: 'met',
      observationRule: 'noon',
      clockMinutes: 720,
      observationAvailable: 1,
    },
    measurements: [
      {
        label: 'Seasonal event',
        value: 'June solstice',
      },
      {
        label: 'Observation',
        value: '2026-06-21 · 1:02:20 PM · solar noon · America/Denver',
      },
      {
        label: 'Sun altitude',
        value: '74.61°',
      },
      {
        label: 'Sun direction',
        value: '180.86° clockwise from north',
      },
      {
        label: 'Height-only shadow reference',
        value: '0.465 m',
      },
      {
        label: 'Target',
        value: 'June · amber light',
      },
      {
        label: 'Expected',
        value: 'amber light',
      },
      {
        label: 'Observed at target centre',
        value: 'amber light',
      },
      {
        label: 'Sculpture surface samples',
        value:
          'Facet 1: faces away; Facet 2: sunlight; Facet 3: sunlight; Facet 4: sunlight; Facet 5: faces away; Facet 6: faces away; Facet 7: faces away; Facet 8: sunlight',
      },
      {
        label: 'Comparison',
        value: 'Matches expectation',
      },
      {
        label: '7 days before',
        value: '2026-06-14: amber light · also matches',
      },
      {
        label: '7 days after',
        value: '2026-06-28: amber light · also matches',
      },
    ],
  },
  {
    settings: {
      latitude: 38.83,
      longitude: -104.82,
      zone: 'America/Denver',
      localDate: '2026-09-22',
      minutes: 773.3352833333333,
      utcInstant: '2026-09-22T18:53:20.117Z',
      modelVersion: 'solar-optics-2.0',
      scenarioId: 'sept',
      reviewId: 'solar-calendar-example',
      targetId: 'equinox',
      expectedValue: 'blue light',
      actualValue: 'blue light',
      outcome: 'met',
      observationRule: 'noon',
      clockMinutes: 720,
      observationAvailable: 1,
    },
    measurements: [
      {
        label: 'Seasonal event',
        value: 'September equinox',
      },
      {
        label: 'Observation',
        value: '2026-09-22 · 12:53:20 PM · solar noon · America/Denver',
      },
      {
        label: 'Sun altitude',
        value: '51.44°',
      },
      {
        label: 'Sun direction',
        value: '180.39° clockwise from north',
      },
      {
        label: 'Height-only shadow reference',
        value: '1.347 m',
      },
      {
        label: 'Target',
        value: 'Equinoxes · blue light',
      },
      {
        label: 'Expected',
        value: 'blue light',
      },
      {
        label: 'Observed at target centre',
        value: 'blue light',
      },
      {
        label: 'Sculpture surface samples',
        value:
          'Facet 1: faces away; Facet 2: sunlight; Facet 3: sunlight; Facet 4: sunlight; Facet 5: faces away; Facet 6: faces away; Facet 7: faces away; Facet 8: sunlight',
      },
      {
        label: 'Comparison',
        value: 'Matches expectation',
      },
      {
        label: '7 days before',
        value: '2026-09-15: shadow · does not match',
      },
      {
        label: '7 days after',
        value: '2026-09-29: shadow · does not match',
      },
    ],
  },
  {
    settings: {
      latitude: 38.83,
      longitude: -104.82,
      zone: 'America/Denver',
      localDate: '2026-12-21',
      minutes: 718.6679666666666,
      utcInstant: '2026-12-21T18:58:40.078Z',
      modelVersion: 'solar-optics-2.0',
      scenarioId: 'dec',
      reviewId: 'solar-calendar-example',
      targetId: 'december',
      expectedValue: 'red light',
      actualValue: 'red light',
      outcome: 'met',
      observationRule: 'noon',
      clockMinutes: 720,
      observationAvailable: 1,
    },
    measurements: [
      {
        label: 'Seasonal event',
        value: 'December solstice',
      },
      {
        label: 'Observation',
        value: '2026-12-21 · 11:58:40 AM · solar noon · America/Denver',
      },
      {
        label: 'Sun altitude',
        value: '27.73°',
      },
      {
        label: 'Sun direction',
        value: '180.27° clockwise from north',
      },
      {
        label: 'Height-only shadow reference',
        value: '3.215 m',
      },
      {
        label: 'Target',
        value: 'December · ruby light',
      },
      {
        label: 'Expected',
        value: 'red light',
      },
      {
        label: 'Observed at target centre',
        value: 'red light',
      },
      {
        label: 'Sculpture surface samples',
        value:
          'Facet 1: faces away; Facet 2: sunlight; Facet 3: sunlight; Facet 4: sunlight; Facet 5: faces away; Facet 6: faces away; Facet 7: faces away; Facet 8: sunlight',
      },
      {
        label: 'Comparison',
        value: 'Matches expectation',
      },
      {
        label: '7 days before',
        value: '2026-12-14: red light · also matches',
      },
      {
        label: '7 days after',
        value: '2026-12-28: red light · also matches',
      },
    ],
  },
] as const;
