/** Generated by node scripts/check-solstice-gates.cjs --write-references. */
export const solsticeObservations = [
  {
    "settings": {
      "latitude": 38.83,
      "longitude": -104.82,
      "zone": "America/Denver",
      "localDate": "2026-03-20",
      "minutes": 454.0987333333333,
      "utcInstant": "2026-03-20T13:34:05.924Z",
      "modelVersion": "solar-optics-2.0",
      "scenarioId": "march",
      "reviewId": "solstice-gates-example",
      "targetId": "observer",
      "expectedValue": "sunlight",
      "actualValue": "sunlight",
      "outcome": "met",
      "observationRule": "morning",
      "clockMinutes": 720,
      "observationAvailable": 1
    },
    "measurements": [
      {
        "label": "Seasonal event",
        "value": "March equinox"
      },
      {
        "label": "Observation",
        "value": "2026-03-20 · 7:34:05 AM · 30 min after sunrise · America/Denver"
      },
      {
        "label": "Sun altitude",
        "value": "5.11°"
      },
      {
        "label": "Sun direction",
        "value": "94.38° clockwise from north"
      },
      {
        "label": "Height-only shadow reference",
        "value": "17.892 m"
      },
      {
        "label": "Target",
        "value": "Center · face east"
      },
      {
        "label": "Expected",
        "value": "sunlight"
      },
      {
        "label": "Observed at target centre",
        "value": "sunlight"
      },
      {
        "label": "Sculpture surface samples",
        "value": "No central object"
      },
      {
        "label": "Comparison",
        "value": "Matches expectation"
      },
      {
        "label": "7 days before",
        "value": "2026-03-13: sunlight · also matches"
      },
      {
        "label": "7 days after",
        "value": "2026-03-27: sunlight · also matches"
      }
    ]
  },
  {
    "settings": {
      "latitude": 38.83,
      "longitude": -104.82,
      "zone": "America/Denver",
      "localDate": "2026-06-21",
      "minutes": 365.6435666666667,
      "utcInstant": "2026-06-21T12:05:38.614Z",
      "modelVersion": "solar-optics-2.0",
      "scenarioId": "june",
      "reviewId": "solstice-gates-example",
      "targetId": "summer-carving",
      "expectedValue": "sunlight",
      "actualValue": "sunlight",
      "outcome": "met",
      "observationRule": "morning",
      "clockMinutes": 720,
      "observationAvailable": 1
    },
    "measurements": [
      {
        "label": "Seasonal event",
        "value": "June solstice"
      },
      {
        "label": "Observation",
        "value": "2026-06-21 · 6:05:38 AM · 30 min after sunrise · America/Denver"
      },
      {
        "label": "Sun altitude",
        "value": "4.45°"
      },
      {
        "label": "Sun direction",
        "value": "63.29° clockwise from north"
      },
      {
        "label": "Height-only shadow reference",
        "value": "20.551 m"
      },
      {
        "label": "Target",
        "value": "Summer carving"
      },
      {
        "label": "Target height",
        "value": "0.566 m above the base · fixed surface mark"
      },
      {
        "label": "Expected",
        "value": "sunlight"
      },
      {
        "label": "Observed at target centre",
        "value": "sunlight"
      },
      {
        "label": "Sculpture surface samples",
        "value": "No central object"
      },
      {
        "label": "Comparison",
        "value": "Matches expectation"
      },
      {
        "label": "7 days before",
        "value": "2026-06-14: sunlight · also matches"
      },
      {
        "label": "7 days after",
        "value": "2026-06-28: sunlight · also matches"
      }
    ]
  },
  {
    "settings": {
      "latitude": 38.83,
      "longitude": -104.82,
      "zone": "America/Denver",
      "localDate": "2026-09-22",
      "minutes": 438.2022,
      "utcInstant": "2026-09-22T13:18:12.132Z",
      "modelVersion": "solar-optics-2.0",
      "scenarioId": "sept",
      "reviewId": "solstice-gates-example",
      "targetId": "observer",
      "expectedValue": "sunlight",
      "actualValue": "sunlight",
      "outcome": "met",
      "observationRule": "morning",
      "clockMinutes": 720,
      "observationAvailable": 1
    },
    "measurements": [
      {
        "label": "Seasonal event",
        "value": "September equinox"
      },
      {
        "label": "Observation",
        "value": "2026-09-22 · 7:18:12 AM · 30 min after sunrise · America/Denver"
      },
      {
        "label": "Sun altitude",
        "value": "5.24°"
      },
      {
        "label": "Sun direction",
        "value": "93.77° clockwise from north"
      },
      {
        "label": "Height-only shadow reference",
        "value": "17.449 m"
      },
      {
        "label": "Target",
        "value": "Center · face east"
      },
      {
        "label": "Expected",
        "value": "sunlight"
      },
      {
        "label": "Observed at target centre",
        "value": "sunlight"
      },
      {
        "label": "Sculpture surface samples",
        "value": "No central object"
      },
      {
        "label": "Comparison",
        "value": "Matches expectation"
      },
      {
        "label": "7 days before",
        "value": "2026-09-15: sunlight · also matches"
      },
      {
        "label": "7 days after",
        "value": "2026-09-29: sunlight · also matches"
      }
    ]
  },
  {
    "settings": {
      "latitude": 38.83,
      "longitude": -104.82,
      "zone": "America/Denver",
      "localDate": "2026-12-21",
      "minutes": 465.40506666666664,
      "utcInstant": "2026-12-21T14:45:24.304Z",
      "modelVersion": "solar-optics-2.0",
      "scenarioId": "dec",
      "reviewId": "solstice-gates-example",
      "targetId": "winter-carving",
      "expectedValue": "sunlight",
      "actualValue": "sunlight",
      "outcome": "met",
      "observationRule": "morning",
      "clockMinutes": 720,
      "observationAvailable": 1
    },
    "measurements": [
      {
        "label": "Seasonal event",
        "value": "December solstice"
      },
      {
        "label": "Observation",
        "value": "2026-12-21 · 7:45:24 AM · 30 min after sunrise · America/Denver"
      },
      {
        "label": "Sun altitude",
        "value": "4.28°"
      },
      {
        "label": "Sun direction",
        "value": "124.91° clockwise from north"
      },
      {
        "label": "Height-only shadow reference",
        "value": "21.360 m"
      },
      {
        "label": "Target",
        "value": "Winter carving"
      },
      {
        "label": "Target height",
        "value": "0.575 m above the base · fixed surface mark"
      },
      {
        "label": "Expected",
        "value": "sunlight"
      },
      {
        "label": "Observed at target centre",
        "value": "sunlight"
      },
      {
        "label": "Sculpture surface samples",
        "value": "No central object"
      },
      {
        "label": "Comparison",
        "value": "Matches expectation"
      },
      {
        "label": "7 days before",
        "value": "2026-12-14: sunlight · also matches"
      },
      {
        "label": "7 days after",
        "value": "2026-12-28: sunlight · also matches"
      }
    ]
  }
] as const;
