import type {
  GoodDefinition,
  MarketDefinition,
  MarketGoodDefinition,
  LocationSceneDefinition,
  SimulationDecisionConfig,
  SimulationEventDefinition,
} from '../../templates/simulation-decision/domain/simulation-decision.models';

const goods = [
  good(
    'fur-pelts',
    'Fur Pelts',
    '◆',
    'Raw materials',
    4_800,
    3,
    'Warm pelts prized at colder mountain posts.',
  ),
  good(
    'flour',
    'Flour',
    '▧',
    'Food',
    2_200,
    2,
    'A staple food that sells steadily in growing settlements.',
  ),
  good('coffee', 'Coffee', '●', 'Food', 3_400, 2, 'A light luxury good with uneven demand.'),
  good(
    'iron-tools',
    'Iron Tools',
    '⚒',
    'Equipment',
    5_200,
    4,
    'Heavy, useful equipment with strong value at remote camps.',
  ),
  good('salt', 'Salt', '◇', 'Food', 1_500, 1, 'Compact, reliable, and useful for preserving food.'),
  good(
    'cloth',
    'Cloth',
    '▱',
    'Textiles',
    2_800,
    2,
    'Flexible cargo with demand in towns and forts.',
  ),
  good(
    'lantern-oil',
    'Lantern Oil',
    '◉',
    'Supplies',
    2_600,
    2,
    'Useful at camps, crossings, and night work sites.',
  ),
  good('sugar', 'Sugar', '■', 'Food', 3_200, 1, 'Small cargo units with luxury-market potential.'),
  good('rope', 'Rope', '◎', 'Equipment', 2_100, 2, 'Practical trail equipment with steady demand.'),
  good(
    'dried-beans',
    'Dried Beans',
    '♢',
    'Food',
    1_800,
    1,
    'Affordable provisions that travel well.',
  ),
] as const;

const events: readonly SimulationEventDefinition[] = [
  {
    id: 'event-river-crossing',
    type: 'decision',
    title: 'Fast Water at the Crossing',
    icon: '≈',
    story:
      'Spring runoff has raised the river. A ferry operator offers a safe crossing, but waiting or taking a detour may preserve more cash. Your company must balance time, cost, and cargo safety.',
    facts: [
      'The normal ford is closed.',
      'Delays use valuable season days.',
      'Cargo remains safe only on the ferry or while waiting.',
    ],
    choices: [
      choice(
        'ferry',
        'Pay for the ferry',
        'Cross safely with little delay.',
        -2_400,
        0,
        'Low risk',
        'The ferry carries the company across safely.',
      ),
      choice(
        'wait',
        'Wait for lower water',
        'Keep most cash but lose a day.',
        -500,
        1,
        'Low risk',
        'The water falls and the trail reopens the next day.',
      ),
      choice(
        'detour',
        'Take the ridge detour',
        'Spend on extra supplies and accept cargo risk.',
        -1_200,
        0,
        'Moderate risk',
        'The longer trail works, but one cargo unit is damaged.',
        1,
      ),
    ],
  },
  {
    id: 'event-supply-bundle',
    type: 'math',
    title: 'Supply Bundle Calculation',
    icon: '÷',
    story:
      'A trail supplier sells four identical repair bundles for $18.00. Your crew needs to know the price of one bundle before deciding whether the offer fits the budget.',
    facts: [
      'The four bundles cost $18.00 total.',
      'All bundles are identical.',
      'Enter the unit price in dollars.',
    ],
    mathChallenge: {
      prompt: '$18.00 ÷ 4 = ?',
      hint: 'Think of 1,800 cents split into four equal groups.',
      answer: 4.5,
      unit: 'dollars',
    },
    choices: [
      choice(
        'buy-bundle',
        'Buy one repair bundle',
        'Use the unit price you calculated.',
        -450,
        0,
        'Known cost',
        'The repair bundle prevents a later delay.',
      ),
      choice(
        'pass-bundle',
        'Save the cash',
        'Continue without the extra repair bundle.',
        0,
        0,
        'Unknown risk',
        'The company keeps its cash and accepts the trail risk.',
      ),
    ],
  },
  {
    id: 'event-demand-order',
    type: 'positive',
    title: 'Camp Supply Order',
    icon: '↑',
    story:
      'A survey crew needs urgent supplies and offers payment for helping organize their delivery list. The work takes a little time but brings dependable income.',
    facts: [
      'Payment is guaranteed.',
      'No cargo is sold.',
      'The task can be completed today or skipped.',
    ],
    choices: [
      choice(
        'help-order',
        'Organize the order',
        'Earn cash for careful record keeping.',
        1_600,
        0,
        'Guaranteed',
        'The accurate list earns your company $16.00.',
      ),
      choice(
        'keep-moving',
        'Keep moving',
        'Protect your schedule instead.',
        0,
        0,
        'No change',
        'The company continues without changing cash.',
      ),
    ],
  },
  {
    id: 'event-wheel-repair',
    type: 'negative',
    title: 'Loose Wagon Wheel',
    icon: '⚙',
    story:
      'A wheel rim has loosened on the rough trail. A careful repair costs money; a temporary fix is cheaper but may damage cargo.',
    facts: [
      'Travel cannot continue without a repair.',
      'A full repair protects cargo.',
      'A temporary fix costs less immediately.',
    ],
    choices: [
      choice(
        'full-repair',
        'Make a full repair',
        'Pay for parts and continue safely.',
        -1_800,
        0,
        'Low risk',
        'The repaired wheel holds for the rest of the route.',
      ),
      choice(
        'temporary-repair',
        'Make a temporary fix',
        'Spend less but risk one cargo unit.',
        -600,
        0,
        'Moderate risk',
        'The wheel holds, but one cargo unit is damaged.',
        1,
      ),
    ],
  },
  {
    id: 'event-reserve-math',
    type: 'math',
    title: 'Reserve Check',
    icon: '%',
    story:
      'The company has $72.00 and considers spending $27.50 on supplies. Calculate the cash that would remain before choosing.',
    facts: [
      'Current comparison amount: $72.00.',
      'Possible supply cost: $27.50.',
      'Enter the remaining dollars.',
    ],
    mathChallenge: {
      prompt: '$72.00 − $27.50 = ?',
      hint: 'Subtract 2,750 cents from 7,200 cents.',
      answer: 44.5,
      unit: 'dollars',
    },
    choices: [
      choice(
        'stock-supplies',
        'Stock extra supplies',
        'Pay now to lower future risk.',
        -2_750,
        0,
        'Low future risk',
        'The crew is well supplied for the remaining trail.',
      ),
      choice(
        'protect-reserve',
        'Protect the reserve',
        'Keep cash for the destination market.',
        0,
        0,
        'Unknown future risk',
        'The company keeps its reserve intact.',
      ),
    ],
  },
  {
    id: 'event-shortcut',
    type: 'decision',
    title: 'Unmarked Shortcut',
    icon: '↗',
    story:
      'A local guide describes a shorter track across open grassland. The route could save a day, but the company would need to pay for guidance.',
    facts: [
      'The shortcut is passable for your transport.',
      'The guide knows the area.',
      'The regular route remains open.',
    ],
    choices: [
      choice(
        'hire-guide',
        'Hire the guide',
        'Pay for local knowledge and keep moving.',
        -1_000,
        0,
        'Low risk',
        'The guide leads the company safely across the shortcut.',
      ),
      choice(
        'regular-route',
        'Stay on the marked route',
        'Spend no extra cash.',
        0,
        1,
        'Low risk',
        'The company follows the longer known trail.',
      ),
    ],
  },
  {
    id: 'event-cargo-cover',
    type: 'negative',
    title: 'Sudden Hail',
    icon: '✦',
    story:
      'A fast hailstorm threatens exposed cargo. Canvas covers are available from another traveler, or the crew can wait beneath a rocky shelter.',
    facts: [
      'Uncovered cargo may be damaged.',
      'The shelter is safe but costs time.',
      'The canvas can be reused.',
    ],
    choices: [
      choice(
        'buy-canvas',
        'Buy canvas covers',
        'Protect cargo and continue.',
        -1_300,
        0,
        'Low risk',
        'The new covers keep every cargo unit dry.',
      ),
      choice(
        'take-shelter',
        'Wait under shelter',
        'Save cash and lose one day.',
        0,
        1,
        'Low risk',
        'The storm passes without damaging cargo.',
      ),
    ],
  },
  {
    id: 'event-distance-math',
    type: 'math',
    title: 'Distance and Pace',
    icon: '×',
    story:
      'The next marker is 36 miles away. At a steady pace of 12 miles per day, calculate how many travel days the segment requires.',
    facts: ['Distance: 36 miles.', 'Pace: 12 miles each day.', 'Enter a whole number of days.'],
    mathChallenge: {
      prompt: '36 miles ÷ 12 miles per day = ?',
      hint: 'How many groups of 12 fit in 36?',
      answer: 3,
      unit: 'days',
    },
    choices: [
      choice(
        'steady-pace',
        'Keep a steady pace',
        'Use the planned three-day schedule.',
        0,
        0,
        'Low risk',
        'The company follows its calculated schedule.',
      ),
      choice(
        'push-harder',
        'Push for a faster pace',
        'Save time but pay for extra feed.',
        -900,
        0,
        'Moderate risk',
        'Extra feed keeps the team moving safely.',
      ),
    ],
  },
  {
    id: 'event-shared-repair',
    type: 'positive',
    title: 'Shared Repair Work',
    icon: '✚',
    story:
      'Another company offers to trade repair help for careful inventory counting. Cooperation can save both groups money.',
    facts: [
      'No cargo changes hands.',
      'The work is completed at camp.',
      'Accurate counting earns a payment.',
    ],
    choices: [
      choice(
        'cooperate',
        'Help with the inventory',
        'Earn money and build goodwill.',
        1_200,
        0,
        'Guaranteed',
        'Both companies finish their repairs and your company earns $12.00.',
      ),
      choice(
        'decline',
        'Decline politely',
        'Keep the evening free.',
        0,
        0,
        'No change',
        'The company rests and continues in the morning.',
      ),
    ],
  },
  {
    id: 'event-price-rumor',
    type: 'decision',
    title: 'Market Price Rumor',
    icon: '!',
    story:
      'A traveler claims that tools are scarce at the next settlement. The claim may help your planning, but it is not verified evidence.',
    facts: [
      'The source is one traveler.',
      'No official market list is available.',
      'Your current cargo cannot change on the trail.',
    ],
    choices: [
      choice(
        'record-rumor',
        'Record it as uncertain evidence',
        'Use the clue carefully in your reflection.',
        0,
        0,
        'Uncertain information',
        'The rumor is saved as context, not as a guaranteed price.',
      ),
      choice(
        'ignore-rumor',
        'Do not use the rumor',
        'Rely only on confirmed market records.',
        0,
        0,
        'No change',
        'The company continues with its existing evidence.',
      ),
    ],
  },
  {
    id: 'event-food-shortage',
    type: 'negative',
    title: 'Trail Food Shortage',
    icon: '−',
    story:
      'The route takes longer than expected and the crew needs more food. Buying locally is expensive, while rationing adds a day.',
    facts: [
      'The crew needs a safe plan.',
      'Food bought here costs more.',
      'Rationing slows travel.',
    ],
    choices: [
      choice(
        'buy-food',
        'Buy trail food',
        'Pay the higher price and stay on schedule.',
        -1_500,
        0,
        'Low risk',
        'The company restocks and continues.',
      ),
      choice(
        'ration',
        'Ration supplies',
        'Keep cash but add a travel day.',
        0,
        1,
        'Low risk',
        'Careful rationing works, though travel slows.',
      ),
    ],
  },
  {
    id: 'event-profit-math',
    type: 'math',
    title: 'Profit per Unit',
    icon: '+',
    story:
      'A trader bought rope for $2.10 per unit and later sold it for $3.25. Calculate the profit on one unit before evaluating the example.',
    facts: [
      'Buy price: $2.10.',
      'Sell price: $3.25.',
      'Profit equals selling price minus buying price.',
    ],
    mathChallenge: {
      prompt: '$3.25 − $2.10 = ?',
      hint: 'Subtract 210 cents from 325 cents.',
      answer: 1.15,
      unit: 'dollars per unit',
    },
    choices: [
      choice(
        'save-example',
        'Save the example',
        'Use it as a strategy reminder.',
        0,
        0,
        'Learning evidence',
        'The calculation is recorded for later reflection.',
      ),
      choice(
        'continue',
        'Continue traveling',
        'Do not save the example.',
        0,
        0,
        'No change',
        'The company continues on the route.',
      ),
    ],
  },
];

export const frontierTradingConfig: SimulationDecisionConfig = {
  schemaVersion: '1.1',
  template: { id: 'simulation-decision', version: '1.1' },
  projectId: 'frontier-trading-company',
  projectVersion: '1.0.0',
  title: 'Frontier Trading Company',
  subtitle: 'Trading Season Simulation',
  gradeLabel: 'Grade 5 Mathematics PBL',
  mission:
    'Build a trading company, use math to manage limited cash and cargo, travel one route, respond to trail events, and defend the strategy with evidence.',
  startingCashCents: 20_000,
  reserveTargetCents: 5_000,
  profitTargetCents: 5_000,
  startingLocationId: 'independence-post',
  maxSeasonDays: 12,
  emblems: [
    { id: 'compass', label: 'Compass', symbol: '✥' },
    { id: 'pine', label: 'Pine tree', symbol: '♠' },
    { id: 'star', label: 'Trail star', symbol: '★' },
    { id: 'wagon', label: 'Wagon wheel', symbol: '⊕' },
  ],
  transports: [
    {
      id: 'prairie-wagon',
      name: 'Prairie Wagon',
      icon: '▣',
      costCents: 4_000,
      cargoCapacity: 30,
      travelSpeed: 1,
      description: 'Balanced capacity and route access.',
      vulnerability: 'Moderate repair risk on rocky ground.',
      compatibleTerrain: ['plains', 'forest', 'river'],
    },
    {
      id: 'mule-train',
      name: 'Mule Train',
      icon: '♞',
      costCents: 3_200,
      cargoCapacity: 20,
      travelSpeed: 1,
      description: 'Smaller loads with excellent terrain access.',
      vulnerability: 'Lower cargo capacity.',
      compatibleTerrain: ['plains', 'forest', 'river', 'mountain', 'rocky'],
    },
    {
      id: 'freight-wagon',
      name: 'Freight Wagon',
      icon: '▰',
      costCents: 5_500,
      cargoCapacity: 42,
      travelSpeed: 0.8,
      description: 'Largest cargo capacity for established roads.',
      vulnerability: 'Cannot use mountain or rocky routes.',
      compatibleTerrain: ['plains', 'forest'],
    },
    {
      id: 'handcart',
      name: 'Handcart Company',
      icon: '◫',
      costCents: 1_800,
      cargoCapacity: 14,
      travelSpeed: 1.2,
      description: 'Low startup cost and quick travel.',
      vulnerability: 'Small reserve and limited rough-terrain access.',
      compatibleTerrain: ['plains', 'forest'],
    },
  ],
  goods,
  locations: [
    {
      id: 'independence-post',
      name: 'Independence Trading Post',
      shortName: 'Independence',
      kind: 'post',
      mapX: 14,
      mapY: 62,
      context: 'A busy starting market with balanced prices and plentiful stock.',
    },
    {
      id: 'fort-bridger',
      name: 'Fort Bridger',
      shortName: 'Fort Bridger',
      kind: 'fort',
      mapX: 38,
      mapY: 30,
      context: 'A northern fort that needs food, cloth, and trail equipment.',
    },
    {
      id: 'river-crossing',
      name: 'Green River Crossing',
      shortName: 'Green River',
      kind: 'crossing',
      mapX: 47,
      mapY: 69,
      context: 'A river settlement with demand for repair goods and preserved food.',
    },
    {
      id: 'south-pass',
      name: 'South Pass Camp',
      shortName: 'South Pass',
      kind: 'pass',
      mapX: 68,
      mapY: 39,
      context: 'A remote mountain camp where heavy tools can earn strong prices.',
    },
    {
      id: 'fort-laramie',
      name: 'Fort Laramie',
      shortName: 'Fort Laramie',
      kind: 'fort',
      mapX: 80,
      mapY: 68,
      context: 'A growing fort with strong household and food demand.',
    },
    {
      id: 'miners-camp',
      name: "Miner's Camp",
      shortName: "Miner's Camp",
      kind: 'camp',
      mapX: 89,
      mapY: 25,
      context: 'A high-risk destination with strong demand for supplies and luxuries.',
    },
  ],
  markets: [
    market(
      'independence-market',
      'independence-post',
      'Independence Market',
      [10_000, 10_200, 9_800, 10_000, 9_500, 10_100, 9_700, 10_300, 9_900, 9_600],
      [8_000, 8_200, 8_100, 8_300, 8_000, 8_100, 8_200, 8_000, 8_300, 8_100],
    ),
    market(
      'bridger-market',
      'fort-bridger',
      'Fort Bridger Market',
      [11_000, 10_800, 10_600, 11_200, 10_300, 10_500, 10_900, 10_700, 10_900, 10_400],
      [14_000, 14_500, 12_000, 13_500, 12_500, 14_200, 13_800, 11_500, 13_000, 14_800],
    ),
    market(
      'river-market',
      'river-crossing',
      'Green River Market',
      [10_700, 10_500, 10_900, 11_000, 10_600, 10_400, 10_300, 10_800, 10_500, 10_200],
      [12_000, 13_700, 12_500, 15_000, 12_800, 12_200, 14_500, 11_800, 14_800, 13_900],
    ),
    market(
      'pass-market',
      'south-pass',
      'South Pass Camp Market',
      [11_500, 11_300, 11_200, 12_000, 11_000, 11_400, 11_600, 11_900, 11_500, 11_000],
      [14_500, 13_000, 13_500, 17_000, 13_800, 12_800, 15_500, 14_200, 15_000, 14_000],
    ),
    market(
      'laramie-market',
      'fort-laramie',
      'Fort Laramie Market',
      [10_800, 10_700, 10_400, 11_000, 10_500, 10_300, 10_700, 10_600, 10_900, 10_300],
      [13_000, 14_200, 13_200, 14_000, 12_500, 15_000, 13_900, 14_700, 12_800, 14_500],
    ),
    market(
      'miners-market',
      'miners-camp',
      "Miner's Camp Market",
      [12_000, 11_500, 11_800, 12_500, 11_300, 11_700, 12_300, 12_200, 12_000, 11_600],
      [16_000, 15_000, 16_500, 18_000, 14_000, 15_500, 17_000, 17_500, 16_000, 15_200],
    ),
  ],
  world: {
    travelAnimationMs: 5_200,
    locations: [
      scene(
        'independence-post',
        'plains',
        'Bright morning with a steady west wind',
        'Mara Bell',
        'Jonas Pike',
        'Nell Avery',
        [
          'Flour shipments are plentiful this week.',
          'Remote camps may pay more for tools.',
          'Fur buyers at the northern fort are asking questions.',
        ],
      ),
      scene(
        'fort-bridger',
        'fort',
        'Cool air and flags snapping above the gate',
        'Ada Rowe',
        'Caleb Stone',
        'June Hale',
        [
          'Food stores are running lower than expected.',
          'Cloth deliveries have been delayed.',
          'A freight crew says coffee demand may soften.',
        ],
      ),
      scene(
        'river-crossing',
        'river',
        'Fast water, drifting clouds, and damp roads',
        'Tessa Green',
        'Micah Ford',
        'Ruth Cole',
        [
          'Repair crews need rope and iron tools.',
          'Travelers are buying dried beans.',
          'River delays could make lantern oil scarce.',
        ],
      ),
      scene(
        'south-pass',
        'mountain',
        'Thin clouds with snow moving over the ridge',
        'Ivy North',
        'Eli Grant',
        'May Chen',
        [
          'Heavy tools are difficult to find here.',
          'Cold nights have raised demand for supplies.',
          'Another trader thinks sugar prices are uncertain.',
        ],
      ),
      scene(
        'fort-laramie',
        'fort',
        'Warm afternoon with wagon traffic at the gate',
        'Clara West',
        'Owen Reed',
        'Sam Ortiz',
        [
          'Households are asking for cloth and flour.',
          'Salt stock looks steady.',
          'A notice claims sugar demand is rising.',
        ],
      ),
      scene(
        'miners-camp',
        'camp',
        'Mountain haze, cook-fire smoke, and busy foot traffic',
        'Rosa Hill',
        'Ben Shaw',
        'Lee Morgan',
        [
          'Tools and lantern oil are visibly scarce.',
          'Freight arrivals have been unreliable.',
          'Luxury prices are high, but the rumor may be exaggerated.',
        ],
      ),
    ],
  },
  routes: [
    {
      id: 'route-northern',
      fromLocationId: 'independence-post',
      toLocationId: 'fort-bridger',
      name: 'Northern Fort Road',
      distanceMiles: 96,
      estimatedDays: 3,
      terrain: ['plains', 'forest'],
      risk: 'low',
      supplyCostCents: 1_800,
      demandClue: 'Food and cloth demand appears steady.',
      path: 'M14 62 C20 42 28 32 38 30',
    },
    {
      id: 'route-river',
      fromLocationId: 'independence-post',
      toLocationId: 'river-crossing',
      name: 'Green River Trail',
      distanceMiles: 108,
      estimatedDays: 4,
      terrain: ['plains', 'river', 'forest'],
      risk: 'moderate',
      supplyCostCents: 2_100,
      demandClue: 'Repair goods and preserved foods may be valuable.',
      path: 'M14 62 C24 72 35 76 47 69',
    },
    {
      id: 'route-south-pass',
      fromLocationId: 'independence-post',
      toLocationId: 'south-pass',
      name: 'South Pass Route',
      distanceMiles: 124,
      estimatedDays: 4,
      terrain: ['plains', 'mountain', 'rocky'],
      risk: 'high',
      supplyCostCents: 2_500,
      demandClue: 'Remote camps often need tools and trail supplies.',
      path: 'M14 62 C31 48 49 39 68 39',
    },
    {
      id: 'route-laramie',
      fromLocationId: 'independence-post',
      toLocationId: 'fort-laramie',
      name: 'Laramie Plains Road',
      distanceMiles: 132,
      estimatedDays: 4,
      terrain: ['plains', 'forest'],
      risk: 'moderate',
      supplyCostCents: 2_300,
      demandClue: 'The growing fort may pay more for cloth and food.',
      path: 'M14 62 C34 61 56 73 80 68',
    },
    {
      id: 'route-miners',
      fromLocationId: 'independence-post',
      toLocationId: 'miners-camp',
      name: 'High Country Freight Trail',
      distanceMiles: 148,
      estimatedDays: 5,
      terrain: ['plains', 'mountain', 'rocky'],
      risk: 'high',
      supplyCostCents: 2_900,
      demandClue: 'Scarce supplies can bring high prices at the mining camp.',
      path: 'M14 62 C37 24 65 16 89 25',
    },
  ],
  events,
  reportSections: [
    {
      id: 'mission-summary',
      title: 'Mission Summary',
      prompt: 'What was your trading company trying to accomplish?',
      evidenceMinimum: 0,
    },
    {
      id: 'starting-strategy',
      title: 'Starting Strategy',
      prompt: 'How did you plan to use cash, cargo space, and route information?',
      evidenceMinimum: 0,
    },
    {
      id: 'best-trade',
      title: 'Best Trade Decision',
      prompt: 'Which trade was strongest? Use a ledger record and explain why.',
      evidenceMinimum: 1,
    },
    {
      id: 'route-risk',
      title: 'Route / Risk Decision',
      prompt: 'How did distance, time, cost, and risk influence your route?',
      evidenceMinimum: 1,
    },
    {
      id: 'change-decision',
      title: 'A Decision You Would Change',
      prompt: 'Which choice would you revise after seeing the outcome?',
      evidenceMinimum: 1,
    },
    {
      id: 'math-evidence',
      title: 'Math Evidence',
      prompt: 'Show a unit-price, budget, or profit calculation that supported a choice.',
      evidenceMinimum: 1,
      calculationRequired: true,
    },
    {
      id: 'season-result',
      title: 'Final Season Result',
      prompt: 'What do the final numbers show about your strategy?',
      evidenceMinimum: 1,
    },
    {
      id: 'strategy-claim',
      title: 'Final Strategy Claim',
      prompt: 'What strategy would you recommend for another season, and why?',
      evidenceMinimum: 2,
    },
    {
      id: 'reflection',
      title: 'Individual Reflection',
      prompt: 'What did you learn about using mathematics to make decisions?',
      evidenceMinimum: 0,
    },
    {
      id: 'submission-check',
      title: 'Submission Checklist',
      prompt: 'Explain how your evidence and calculations support your final claim.',
      evidenceMinimum: 0,
    },
  ],
};

function good(
  id: string,
  name: string,
  icon: string,
  category: string,
  baseBuyPriceCents: number,
  unitCargo: number,
  description: string,
): GoodDefinition {
  return { id, name, icon, category, baseBuyPriceCents, unitCargo, description };
}

function choice(
  id: string,
  label: string,
  description: string,
  cashChangeCents: number,
  dayChange: number,
  riskLabel: string,
  outcome: string,
  inventoryLossQuantity?: number,
) {
  return {
    id,
    label,
    description,
    cashChangeCents,
    dayChange,
    riskLabel,
    outcome,
    inventoryLossQuantity,
  };
}

function market(
  id: string,
  locationId: string,
  name: string,
  buyMultipliers: readonly number[],
  sellMultipliers: readonly number[],
): MarketDefinition {
  const marketGoods: MarketGoodDefinition[] = goods.map((item, index) => {
    const buy = buyMultipliers[index] ?? 10_000;
    const sell = sellMultipliers[index] ?? 10_000;
    return {
      goodId: item.id,
      availableQuantity: 12 + ((index * 7 + name.length) % 19),
      buyMultiplierBps: buy,
      sellMultiplierBps: sell,
      trend: sell > 13_000 ? 'higher' : sell < 10_000 ? 'lower' : 'same',
      note:
        sell > 14_000
          ? 'Strong local demand'
          : sell < 10_000
            ? 'Plentiful local supply'
            : 'Steady local trade',
    };
  });
  return { id, locationId, name, statusText: 'Open for trading', goods: marketGoods };
}

function scene(
  locationId: string,
  environment: LocationSceneDefinition['environment'],
  weather: string,
  generalMerchant: string,
  smith: string,
  freightMerchant: string,
  rumors: readonly string[],
): LocationSceneDefinition {
  const stall = (
    suffix: string,
    name: string,
    merchantName: string,
    merchantRole: string,
    icon: string,
    categories: readonly string[],
    greeting: string,
    rumor: string,
    trustCue: string,
  ) => ({
    id: `${locationId}-${suffix}`,
    name,
    merchantName,
    merchantRole,
    icon,
    categories,
    greeting,
    rumor,
    trustCue,
  });

  return {
    locationId,
    environment,
    weather,
    arrivalText: `Your wagon rolls into a ${environment} trading stop. Inspect the stalls before committing company money.`,
    stalls: [
      stall(
        'general-store',
        'General Store',
        generalMerchant,
        'Store owner',
        '▤',
        ['Food', 'Textiles', 'Supplies'],
        'Welcome, trader. Check the posted prices and leave room in that wagon.',
        rumors[0] ?? 'Travelers report changing demand farther west.',
        'Posted prices and visible shelf stock are verified here.',
      ),
      stall(
        'blacksmith',
        'Blacksmith',
        smith,
        'Blacksmith',
        '⚒',
        ['Equipment'],
        'Tools cost coin, but a well-chosen load can earn it back on the trail.',
        rumors[1] ?? 'Freight crews have been asking about repair tools.',
        'Current workshop orders support part of this claim.',
      ),
      stall(
        'freight-depot',
        'Freight Depot',
        freightMerchant,
        'Freight agent',
        '▰',
        ['Raw materials'],
        'Space is money. Compare profit per cargo space before loading up.',
        rumors[2] ?? 'A wagon master expects raw materials to move soon.',
        'This is a traveler report and may be uncertain.',
      ),
      stall(
        'notice-board',
        'Notice Board',
        'Town notices',
        'Posted intelligence',
        '✦',
        [],
        'Read the notices, then decide which claims deserve your trust.',
        rumors.join(' '),
        'Notices mix verified prices with unconfirmed market rumors.',
      ),
    ],
  };
}
