import type { RouteDefinition } from '../../templates/simulation-decision/domain/simulation-decision.models';

function trail(
  id: string,
  from: string,
  to: string,
  name: string,
  path: string,
  days: number,
  miles: number,
  terrain: readonly string[],
  risk: RouteDefinition['risk'],
  cost: number,
): RouteDefinition {
  return {
    id,
    fromLocationId: from,
    toLocationId: to,
    name,
    path,
    estimatedDays: days,
    distanceMiles: miles,
    terrain,
    risk,
    supplyCostCents: cost,
    demandClue:
      'Check the market news. Weather, disrupted freight and arriving shipments can change prices.',
  };
}

function link(
  id: string,
  from: string,
  to: string,
  name: string,
  points: readonly [number, number, number, number, number, number, number, number],
  days: number,
  miles: number,
  terrain: readonly string[],
  risk: RouteDefinition['risk'],
  cost: number,
): RouteDefinition[] {
  const [x1, y1, cx1, cy1, cx2, cy2, x2, y2] = points;
  return [
    trail(
      id,
      from,
      to,
      name,
      `M${x1} ${y1} C${cx1} ${cy1} ${cx2} ${cy2} ${x2} ${y2}`,
      days,
      miles,
      terrain,
      risk,
      cost,
    ),
    trail(
      `${id}-return`,
      to,
      from,
      `${name} · return`,
      `M${x2} ${y2} C${cx2} ${cy2} ${cx1} ${cy1} ${x1} ${y1}`,
      days,
      miles,
      terrain,
      risk,
      cost,
    ),
  ];
}

/** Authored regional connections and return roads extend the original five departure choices. */
export const frontierNetworkRoutes: readonly RouteDefinition[] = [
  trail(
    'route-northern-return',
    'fort-bridger',
    'independence-post',
    'Northern Fort Road · return',
    'M38 30 C28 32 20 42 14 62',
    3,
    96,
    ['plains', 'forest'],
    'low',
    1800,
  ),
  trail(
    'route-river-return',
    'river-crossing',
    'independence-post',
    'Green River Trail · return',
    'M47 69 C35 76 24 72 14 62',
    4,
    108,
    ['plains', 'river', 'forest'],
    'moderate',
    2100,
  ),
  trail(
    'route-south-pass-return',
    'south-pass',
    'independence-post',
    'South Pass Route · return',
    'M68 39 C49 39 31 48 14 62',
    4,
    124,
    ['plains', 'mountain', 'rocky'],
    'high',
    2500,
  ),
  trail(
    'route-laramie-return',
    'fort-laramie',
    'independence-post',
    'Laramie Supply Road · return',
    'M80 68 C56 73 34 61 14 62',
    3,
    118,
    ['plains', 'forest'],
    'low',
    2200,
  ),
  trail(
    'route-miners-return',
    'miners-camp',
    'independence-post',
    'High Country Freight Trail · return',
    'M89 25 C65 16 37 24 14 62',
    5,
    148,
    ['plains', 'mountain', 'rocky'],
    'high',
    2900,
  ),
  ...link(
    'route-bridger-river',
    'fort-bridger',
    'river-crossing',
    'Riverbank Connector',
    [38, 30, 31, 44, 39, 59, 47, 69],
    2,
    58,
    ['forest', 'river'],
    'moderate',
    1100,
  ),
  ...link(
    'route-river-laramie',
    'river-crossing',
    'fort-laramie',
    'Valley Freight Road',
    [47, 69, 60, 76, 75, 73, 80, 68],
    2,
    64,
    ['plains'],
    'low',
    1200,
  ),
  ...link(
    'route-laramie-pass',
    'fort-laramie',
    'south-pass',
    'Eastern Ridge Road',
    [80, 68, 84, 53, 74, 46, 68, 39],
    2,
    52,
    ['plains', 'forest'],
    'moderate',
    1400,
  ),
  ...link(
    'route-bridger-pass',
    'fort-bridger',
    'south-pass',
    'Fort-to-Pass Road',
    [38, 30, 49, 25, 58, 30, 68, 39],
    2,
    61,
    ['plains', 'forest'],
    'moderate',
    1400,
  ),
  ...link(
    'route-pass-miners',
    'south-pass',
    'miners-camp',
    'High Camp Switchbacks',
    [68, 39, 76, 39, 87, 33, 89, 25],
    2,
    43,
    ['mountain', 'rocky'],
    'high',
    1600,
  ),
  ...link(
    'route-laramie-miners',
    'fort-laramie',
    'miners-camp',
    'Camp Supply Loop',
    [80, 68, 98, 54, 99, 37, 89, 25],
    3,
    84,
    ['plains', 'forest'],
    'moderate',
    1900,
  ),
  ...link(
    'route-bridger-laramie',
    'fort-bridger',
    'fort-laramie',
    'Central Trading Road',
    [38, 30, 49, 49, 67, 54, 80, 68],
    3,
    88,
    ['plains', 'forest'],
    'low',
    1700,
  ),
];
