import type { SimulationDecisionConfig } from './simulation-decision.models';
import type {
  ExpeditionAction,
  ExpeditionCycle,
  ExpeditionState,
} from './expedition-course.models';
import { createExpedition, reduceExpedition } from './expedition-course.engine';

/** An explicitly labelled practice journey, generated by the same accounting rules. */
export function exampleExpedition(
  config: SimulationDecisionConfig,
  cycle: ExpeditionCycle,
): ExpeditionState {
  let state = createExpedition(config, cycle);
  const act = (action: ExpeditionAction) => {
    state = reduceExpedition(config, cycle, state, action).state;
  };
  act({ type: 'trade', goodId: cycle.goodIds[0]!, direction: 'buy', quantity: 6 });
  for (const target of [...cycle.requiredLocationIds, config.startingLocationId]) {
    const queue: { at: string; path: string[] }[] = [{ at: state.locationId, path: [] }];
    const seen = new Set<string>();
    let path: string[] = [];
    while (queue.length) {
      const node = queue.shift()!;
      if (node.at === target) {
        path = node.path;
        break;
      }
      if (seen.has(node.at)) continue;
      seen.add(node.at);
      for (const leg of cycle.legs) {
        const road = config.routes.find((r) => r.id === leg.routeId)!;
        if (road.fromLocationId === node.at)
          queue.push({ at: road.toLocationId, path: [...node.path, road.id] });
      }
    }
    for (const routeId of path) {
      act({ type: 'depart', routeId });
      for (let guard = 0; state.travel && guard < 100; guard++) {
        if (state.pendingHazardId) {
          const hazard = cycle.hazards.find((h) => h.id === state.pendingHazardId)!;
          act({ type: 'resolve', choiceId: hazard.choices.find((c) => c.costCents === 0)!.id });
        } else act({ type: 'advance' });
      }
    }
    if (target === cycle.requiredLocationIds.at(-1)) {
      for (const [goodId, item] of Object.entries(state.inventory)) {
        if (item.quantity)
          act({ type: 'trade', goodId, direction: 'sell', quantity: item.quantity });
      }
    }
  }
  return {
    ...state,
    feedback: 'Practice journey. File its receipts, then check the cash balance.',
  };
}
